In [37]:
import numpy as np
#NumPy ka full form hai Numerical Python, aur ye ek Python library hai jo mainly numerical calculations 
#aur array-based computing ke liye use hoti hai. Iska use scientific computing, data analysis, machine learning,
# aur deep learning mein bhi hota hai.'''

In [38]:
#creating 1-D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [39]:
arr1=np.array([1,2,3,4,5])
arr1.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [40]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [41]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [42]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
##identity matrix
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
arr2.dtype

dtype('int64')

In [45]:
arr2.size

10

In [46]:
arr2.itemsize

8

In [47]:
arr2.ndim

2

In [48]:
###Numpy vectorized operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([5,6,7,8,9])
print("Addition",arr1+arr2)
print("Substraction:",arr1-arr2)
#similarly multiplication and division

Addition [ 6  8 10 12 14]
Substraction: [-4 -4 -4 -4 -4]


In [49]:
##Universal fucntion
arr=np.array([4,5,6,7,3])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))



[2.         2.23606798 2.44948974 2.64575131 1.73205081]
[  54.59815003  148.4131591   403.42879349 1096.63315843   20.08553692]
[-0.7568025  -0.95892427 -0.2794155   0.6569866   0.14112001]
[1.38629436 1.60943791 1.79175947 1.94591015 1.09861229]


In [50]:
##slicing and indexing
arr4=np.array([[1,2,3,4],[2,3,4,5],[4,5,6,7]])
print(arr4)



[[1 2 3 4]
 [2 3 4 5]
 [4 5 6 7]]


In [51]:
arr4[0][3]

np.int64(4)

In [52]:
print(arr4[0:2,2:])

[[3 4]
 [4 5]]


In [53]:
##modifying array element
arr4[0,0]=100
arr4[1:]=100
print(arr4)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [54]:
##normalization-mean-0, standard dev=1
data=np.array([1,2,3,4,5])
mean=np.mean(data)
std_dev=np.std(data)
normalized_data=(data-mean)/std_dev
print("Normalized_data",normalized_data)

Normalized_data [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [55]:
median=np.median(data)
variance=np.var(data)
print(median)
print(variance)

3.0
2.0


In [56]:
#logical operations
data=np.array([1,2,3,4,5,5,6,67,7])
data[(data>=5)  &(data<10)]

array([5, 5, 6, 7])